-- CREATE DATABASE logic;
USE LOGIC;
-- CREATE TABLE STUDENT ( ID INT PRIMARY KEY , NAME VARCHAR(30) , ROLE VARCHAR(10));
-- INSERT INTO STUDENT VALUES (1,"PRANESH","CEO"),
-- 			(2,"PRANESH","MANAGER"),
--             (3,"PRANESH","HR"),
--             (4,"PRANESH","EMPLOYEE");
            
SELECT * FROM STUDENT;

SELECT * FROM STUDENT ORDER BY ROLE;

SELECT * FROM STUDENT ORDER BY (CASE ROLE
 WHEN 'EMPLOYEE' THEN 1
 WHEN 'CEO' THEN 2
 ELSE 100 END);
